name: Update Tailwind Plus Templates
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
jobs:
  crawl-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tailwindplus Crawler Action
        uses: TenschertSoftware/tailwindplus-crawler-action@main
        with:
          email: ${{ secrets.TAILWINDPLUS_EMAIL }}
          password: ${{ secrets.TAILWINDPLUS_PASSWORD }}
          output: TenschertSoftware/TailwindPlus
          branch: main  # output branch
          outputfolder: ./
          actor: ${{ secrets.BOT_ACTOR }}
          token: ${{ secrets.BOT_TOKEN }}
          commitmessage: "Update Tailwind Plus"
          crawler: ${{ github.repository }}
          crawlerref: ${{ github.ref }}
          current_branch: ${{ github.ref }}
        env:
          LANGUAGES: html,react,vue,alpine
          COMPONENTS: all
          BUILDINDEX: 1
          TEMPLATES: 1
          FORCE_UPDATE: 0
          DEBUG: 0
